// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcS2BY3Ex5BHhHd6BTihmApFwlTh-bBO8',
    appId: '1:649787522335:web:63336601afd9f2b7b8842a',
    messagingSenderId: '649787522335',
    projectId: 'iita-bbest-app',
    authDomain: 'iita-bbest-app.firebaseapp.com',
    storageBucket: 'iita-bbest-app.firebasestorage.app',
    measurementId: 'G-T76Z0NKETJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQRdNqVFIwUVmELJK7T3ObHXUUg5ImUw',
    appId: '1:649787522335:android:6b18c1fd82b6a20fb8842a',
    messagingSenderId: '649787522335',
    projectId: 'iita-bbest-app',
    storageBucket: 'iita-bbest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vhuEttPQ0UxHSuKBPxPwHMzrOcqbf_k',
    appId: '1:649787522335:ios:543d879c1c7a4307b8842a',
    messagingSenderId: '649787522335',
    projectId: 'iita-bbest-app',
    storageBucket: 'iita-bbest-app.firebasestorage.app',
    iosBundleId: 'com.example.iitaBbestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3vhuEttPQ0UxHSuKBPxPwHMzrOcqbf_k',
    appId: '1:649787522335:ios:543d879c1c7a4307b8842a',
    messagingSenderId: '649787522335',
    projectId: 'iita-bbest-app',
    storageBucket: 'iita-bbest-app.firebasestorage.app',
    iosBundleId: 'com.example.iitaBbestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcS2BY3Ex5BHhHd6BTihmApFwlTh-bBO8',
    appId: '1:649787522335:web:f650fc7f859aecedb8842a',
    messagingSenderId: '649787522335',
    projectId: 'iita-bbest-app',
    authDomain: 'iita-bbest-app.firebaseapp.com',
    storageBucket: 'iita-bbest-app.firebasestorage.app',
    measurementId: 'G-WW1LXZ95D4',
  );
}